### ISSUE TITLE
Make compatible with other font face implemenations besides freetype

### ISSUE THREAD

**Issue by CamilleScholtz** [AndreKR/multiface#1]
Would this be possible, so instead of taking a freetype.Face taking an interface?

**Comment by AndreKR** [comment]
Maybe, which one exactly?

**Comment by AndreKR** [comment]
@onodera-punpun Maybe, which implementation exactly?

The reason why we're taking a `truetype.Font` is that we need access to the `.Index()` method to check if the font has a glyph for a character.

I would be reluctant to directly define an interface `multiface.Indexer` that contains an `.Index()` method. While this would immediately be satisfied by a `truetype.Font`, I don't think that is a good API for `multiface`.

The best way would probably be to define an interface `multiface.GlyphChecker` or something like that with a method `.HasGlyph(r rune)` and then provide wrapper structs for `truetype.Font` and \<your implementation\> that implement `.HasGlyph()` and forward the call to whatever method a font format uses to check glyph existence.

**Comment by CamilleScholtz** [comment]
I'm personally using https://github.com/zachomedia/go-bdf, though it would be ideal if every font face implementation could be supported in some way. If this is not possible I'll just fork the package and create a bdf version :). If possible, because it doesn't seem to have this index function.

**Comment by AndreKR** [comment]
Turns out I had already added code to handle well-behaved font.Faces, I just hadn't exposed it to prevent others from accidentally using it with Truetype fonts.

I now added an AddFace() method that you can use to add your BDF font.Face.

**Comment by CamilleScholtz** [comment]
Thanks a lot!
